language: java
dist: trusty # 2019-08-06 Travis only supports Android builds on Trusty
sudo: false
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
script:
  - ./gradlew test
matrix:
  include:
    - language: android
      android:
        components:
          - build-tools-29.0.0
          - android-29
